{"version":3,"file":"test.validation.error.js","sourceRoot":"","sources":["test.validation.error.ts"],"names":[],"mappings":"AAAA,IAAI,CAAE,yDAAyD,EAAE,GAAG,EAAE;IACrE,IAAI;QACH,MAAM,IAAI,eAAe,CAAE,0BAA0B,CAAE,CAAA;KACvD;IAAC,OAAQ,EAAE,EAAG;QACd,MAAM,CAAE,EAAE,CAAC,OAAO,CAAE,CAAC,IAAI,CAAE,0BAA0B,CAAE,CAAA;KACvD;AACF,CAAC,CAAE,CAAA","sourcesContent":["test( 'should be able to throw a validation error with message', () => {\n\ttry {\n\t\tthrow new ValidationError( 'validation_error_occured' )\n\t} catch ( ex ) {\n\t\texpect( ex.message ).toBe( 'validation_error_occured' )\n\t}\n} )\n"]}